wrappers/wrappers.go
When using the NextBatch wrapper, NextBatch calls the provided next
function until a non-SSPluginSuccess value is returned.
There was a bug in this, where a timeout from the underlying next
function would be passed up to the framework, even if there were some
pending events (think fewer than max batch size).
The fix is to change a timeout to success if there are any events to
return.
Signed-off-by: Mark Stemm <mark.stemm@gmail.com>
/kind bug
> /kind design
> /area build
> /area tests …
=> plugin_next_batch should return success when batch < max batch size

wrappers/wrappers.go
```
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
Co-authored-by: Jason Dellaluce <jasondellaluce@gmail.com>
Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
```
/kind bug
Fixes ParamTypeUint64 switch case in RegisterAsyncExtractors to properly set the `field_present` bool and `res_u64` value when present is true.
Fixes #
```release-note
Fixes uint64 usage in async extractor.
```
=> fix(wrappers): properly reverse if check in async extractor

pkg/sdk/extract.go
/kind design
/kind feature
This adds the `FieldType()` accessor to the `sdk.ExtractRequest` interface. This is useful in field extraction to implement type-based reasoning and to potentially achieve better performance.
Without this accessor, plugin developers need to maintain knowledge about the type of each supported field across multiple code parts, which leads to a more verbose and dirty codebase. 
```release-note
NONE
```
=> update: add accessor for field type in ExtractRequest

examples/custom/custom.go, examples/extractor/extractor.go, examples/full/full.go, pkg/sdk/extract.go
/kind design
/kind feature
This removes the type-specific `SetU64Value` and `SetStrValue` methods from the `ExtractRequest` interface, to add a type-agnostic `SetValue(v interface{}` method instead. This brings the following benefits:
1. The interface will never change once new field types are supported (it will not be a breaking change)
2. Plugin codebases can become cleaner, as they don't have to be mindful of type-specific cases
3. Type checking is handled internally: better control (setting a wrong type leads to a panic), and better error handling (the panic message explicitly communicates which type casting failed).
4. Type casting is fairly …
=> refactor: use a type-agnostic SetValue method in ExtractRequest

pkg/sdk/sdk.go
Plugin events are no longer capped at 64k, and we think 64k might be
too small for some plugins, so change the default to 256k.
Signed-off-by: Mark Stemm <mark.stemm@gmail.com>
/kind bug
> /kind design
> /area build
> /area tests
Fixes #
```release-note
NONE
```
=> Increase the default event limit to 256k

pkg/ptr/bytes.go, pkg/ptr/bytes_test.go, pkg/ptr/string_test.go, pkg/sdk/event_test.go, pkg/sdk/extract_test.go, pkg/sdk/plugins/extractor/extractor_test.go, pkg/sdk/plugins/plugins_test.go, pkg/sdk/plugins/source/source_test.go, pkg/sdk/symbols/evtstr/evtstr_test.go, pkg/sdk/symbols/extract/extract.go, pkg/sdk/symbols/extract/extract_test.go, pkg/sdk/symbols/fields/fields_test.go, pkg/sdk/symbols/info/info.go, pkg/sdk/symbols/info/info_test.go, pkg/sdk/symbols/initialize/initialize_test.go, pkg/sdk/symbols/lasterr/lasterr_test.go, pkg/sdk/symbols/nextbatch/nextbatch_test.go, pkg/sdk/symbols/open/open_test.go, pkg/sdk/symbols/progress/progress_test.go
/kind cleanup
/kind feature
/area tests
This adds a bunch of unit tests in every package of the SDK. The prebuilt C symbols of the plugin framework are tested as well. This can be a valuable regression testing tool for future SDK updates.
Thanks to the new test suite, a miro bug has also been fixed in the `ptr` package.
The new coverage results are reported below:
```
$ make test
ok      github.com/falcosecurity/plugin-sdk-go/pkg/cgo  (cached)        coverage: 86.7% of statements
ok      github.com/falcosecurity/plugin-sdk-go/pkg/ptr  (cached)        coverage: 97.2% of statements
ok      github.com/falcosecurity/plugin-sdk-go/pkg/sdk  0.019s …
```
=> test: introducing tests in every package and increase coverage

.circleci/config.yml, .goreleaser.yml, release.md
/kind documentation
/kind feature
/area build
This PR introduces a simple and already test mechanism to generate the changelog when tagging a release.
It basically uses [GoReleaser](https://github.com/goreleaser/goreleaser) (running on a CircleCI job).
The changelog will be based on commit messages that adhere to [convetionalcommit](https://www.conventionalcommits.org/en/v1.0.0/) spec.
Note that we are intentionally ignoring release-note block for the moment since it would be too cumbersome for the current size of this project. However, I suggest keeping the release-note block in the PR template since it can be very informative regarding the PR purpose.
**Which …
=> build: release system with goreleaser

pkg/sdk/event.go, pkg/sdk/extract.go
Signed-off-by: Luca Guerra <luca@guerra.sh>
/kind bug
> /kind design
> /area build
> /area plugin-sdk
> /area tests
When attempting to compile a plugin on MacOS the process will fail because of an error like `../../../../go/pkg/mod/github.com/falcosecurity/plugin-sdk-go@v0.0.0-20211105150954-f1111dfdc937/pkg/sdk/event.go:173:9: cannot use _Ctype_ulong(_Ciconst_UINT64_MAX) (type _Ctype_ulong) as type _Ctype_ulonglong in assignment`
If you change that as the error suggests, you'll get the opposite error on …
=> Use uint64_t to prevent long/longlong confusion

pkg/sdk/internal/hooks/hooks.go, pkg/sdk/plugins/extractor/extractor.go, pkg/sdk/symbols/extract/async.go, pkg/sdk/symbols/extract/extract.c, pkg/sdk/symbols/extract/extract.h, pkg/sdk/symbols/extract/internal/asyncbench/async.go, pkg/sdk/symbols/extract/internal/asyncbench/async_test.go, pkg/sdk/symbols/extract/internal/asyncbench/bench.c, pkg/sdk/symbols/extract/internal/asyncbench/bench.h, pkg/sdk/symbols/extract/internal/asyncbench/workload.go, pkg/sdk/symbols/initialize/initialize.go
/kind feature
For deeper context, see https://github.com/falcosecurity/plugin-sdk-go/issues/25. This PR improves async extraction by:
- Adding a reproducible benchmark suite, which helped us understanding how to improve the async worker
- Adding an automatic feasibility detection based on the number of CPUs. For now, async extraction is available if at least two CPUs are available.
- Enabling async extraction by default (if feasible), and allowing plugin developers to disable/enable it during the plugin initialization.
- Improving the async worker by using a shared spinlock between the C and Go runtimes. This avoids the need of a Go -> C call that …
=> refactor: improve async extraction with automatic activation and benchmarks

pkg/sdk/internal/hooks/hooks.go, pkg/sdk/plugins/extractor/extractor.go, pkg/sdk/symbols/initialize/initialize.go
/kind bug
/kind feature
This fixes a bug that caused some internal hook calls to be shadowed. in the `extractor.Register` function, a callback to `extract.StartAsync` is set through the `initialize.SetOnInit` function. However, that may be overridden if `source.Register` is called after `extractor.Register`. This is currently reproducible in the `full` example. As for documentation, there should not be an ordering constraint for how the two `*.Register` functions are called.
This causes the `extract.StartAsync` function to potentially not being called. However, this `extract.StopAsync` is …
=> update: fix hook shodowing by refining event granularity

pkg/sdk/plugins/extractor/extractor.go
/kind bug
In some edge cases, `extract.StopAsync` can could be invoked without `extract.StartAsync` being invoked first, which is semantically wrong (it also leads to a panic). This PR fixes this by setting up the `extract.StopAsync` callback only after `extract.StartAsync` is effectively invoked.
```release-note
NONE
```
=> fix(sdk/plugins/extractor): safely set async extractor stop hook

pkg/sdk/sdk.go, pkg/sdk/symbols/fields/fields_test.go
Allow field properties to be a list of strings, to allow specifying
more than one property for a field.
Signed-off-by: Mark Stemm <mark.stemm@gmail.com>
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area tests
Fixes #
```release-note
NONE
```
=> Allow field properties to be a list of strings

examples/extractor/extractor.go, examples/full/full.go, examples/full/go.mod, examples/full/go.sum, examples/source/source.go, pkg/sdk/symbols/info/info.c, pkg/sdk/symbols/info/info.go, pkg/sdk/symbols/info/info.h
/kind feature
This supports a default value for `plugin_required_api_version` that removes the requirement of setting the `RequiredAPIVersion` info field for plugin developers. The value can still be specified to override the default one. The default value is grabbed from `plugin_info.h`.
```release-note
update: set default required api version
```
=> update: set default required api version

pkg/sdk/extract.go, pkg/sdk/extract_test.go, pkg/sdk/sdk.go, pkg/sdk/symbols/extract/extract_test.go
/kind cleanup
/kind design
During the development of the plugin system, the enumeration of fields for field extraction has been divorced from the one used internally by libsinsp. In the SDK Go, the enum constants still reflect the enumeration in libsinsp. This is now changed to only respect the enumeration of the plugin framework.
```release-note
update(sdk): divorce field type enumeration
```
=> update(sdk): divorce field type enumeration

pkg/sdk/symbols/extract/extract.c
Make sure we set the dllexport attribute on plugin_extract_fields when
we're building for Windows.
Signed-off-by: Gerald Combs <gerald@wireshark.org>
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area tests
It ensures that plugin_extract_fields is callable on Windows.
Fixes #
```release-note
NONE
```
=> update(sdk): Export plugin_extract_fields on Windows.

examples/extractor/extractor.go, examples/full/full.go, examples/source/source.go, pkg/sdk/plugins/extractor/extractor.go, pkg/sdk/plugins/plugins.go, pkg/sdk/plugins/source/source.go, pkg/sdk/plugins/source/source_test.go
/kind bug
/kind design
/kind feature
> /area build
> /area tests
This PR changes the way we initialize the plugin object in the SDK in order to support multiple re-initializations.
See `SetFuctory()` comment for more detail.
Fixes #
```release-note
new(pkg/sdk/plugins): introduce FactoryFunc and SetFactory()
```
=> fix: subsequent init support

examples/source/source.go, pkg/sdk/event_test.go, pkg/sdk/inmemory.go, pkg/sdk/internal/sdk/inmemory.go, pkg/sdk/plugins/source/instance.go, pkg/sdk/plugins/source/instance_test.go, pkg/sdk/sdk.go
/kind feature
/area tests
This PR introduces two builtin implementations of the `source.Instance` interface of the `sdk/plugins/source` package. This interface is responsible of representing opened event sources and of producing event data through the `NextBatch()` method.
There are two built-in implementations provided, each implemented for its use case:
- _"Pull model"_: for use cases in which the event source can be implemented sequentially and the time required to generate a sequence of event is deterministic. This is implemented with a functional design, where the passed-in callback is expected to be non-suspensive and to return quickly.
- …
=> new(sdk/plugins): add builtin event stream instance implementations for push and pull models

pkg/sdk/symbols/extract/async.go
/kind bug
This PR fixes the sleeping policy of the async extractor. Currently, the starvation time is not calculated properly, which in the general case can lead to the async worker to never sleep and consume lots of CPU time (I was able to reproduce 100% usage in my setup). With this fix, extraction-intensive use case seem to not be affected performance-wise, whereas plugins where extraction don't happens have just a 1.5%-3% CPU usage overhead if the async extractor is enabled, which is acceptable given its benefits. …
=> fix(sdk/symbols/extract): properly calculate starvation time in async extractor

OWNERS
/kind documentation
This PR supersedes #58 since it is blocked by a reviewer "change request". 
Note that all the maintainers moved to emeritus have been:
- inactive in the last 6 months,
- stepped down,
- or never contributed to this repository
Fixes #
```release-note
NONE
```
=> update(OWNERS): move inactive maintainers to emeritus

Makefile, benchmarks/async/bench.cpp, pkg/sdk/event.go, pkg/sdk/extract.go, pkg/sdk/plugin_api.h, pkg/sdk/plugin_types.h, pkg/sdk/symbols/doc.go, pkg/sdk/symbols/evtstr/evtstr.go, pkg/sdk/symbols/extract/extract.go, pkg/sdk/symbols/extract/extract.h, pkg/sdk/symbols/fields/fields.go, pkg/sdk/symbols/info/info.c, pkg/sdk/symbols/initialize/initialize.go, pkg/sdk/symbols/initschema/initschema.go, pkg/sdk/symbols/lasterr/lasterr.go, pkg/sdk/symbols/listopen/listopen.go, pkg/sdk/symbols/nextbatch/nextbatch.go, pkg/sdk/symbols/open/open.go, pkg/sdk/symbols/progress/progress.go
/kind cleanup
/area build
This updates the libs version used by the SDK after the changes of https://github.com/falcosecurity/libs/pull/392, which splitted the `plugin_info.h` file in different parts.
```release-note
update: bump libs version to 5b9c3ca9ae55800e774e1681a0c5e7d54ca89263
```
=> update: bump libs version to 5b9c3ca9ae55800e774e1681a0c5e7d54ca89263

Makefile, benchmarks/async/go.sum, examples/custom/go.sum, examples/extractor/go.sum, examples/full/go.sum, examples/source/go.sum, go.mod, go.sum, pkg/loader/loader.go, pkg/loader/plugin_loader.c, pkg/loader/plugin_loader.h
/kind feature
After the changes in libs of https://github.com/falcosecurity/libs/pull/392 (~yet to get merged~), the plugin loading code is isolated in a self-contained package and implements a C api. As such, it is possible to develop loaders in other programming languages by reusing the libs one, which makes it compliant with the targeted libs version out of the box.
This first version of the loader is capable of loading plugins, validating them against the currently-supported plugin API version, and reading all their static/descriptive information (name, version, etc...). The loader is also capable of …
=> new: introduce plugin loader code

pkg/sdk/plugins/extractor/extractor.go, pkg/sdk/symbols/extract/async.go, pkg/sdk/symbols/extract/async_test.go, pkg/sdk/symbols/extract/extract.c, pkg/sdk/symbols/extract/extract.h
/kind feature
Following up the discussion of #62, this PR implements the **P3-S4** approach to support concurrent extraction request with the async extraction optimization. The design is as follows.
We have **N** concurrent consumers from the C world, **N** locks shared between C and Go, and **M** async workers in the Go world. The shared spinlocks are the point of synchronization between the C consumers and the Go workers. There is a 1-1 mapping between a C consumer and a shared lock, so there are no collisions between consumers on the same lock. As such, each consumer will be served always by the same one worker. On the contrary, each worker …
=> refactor(pkg/sdk/symbols/extract): support concurrent consumers in async extraction optimization

pkg/cgo/handle.go, pkg/sdk/symbols/extract/async_test.go
/kind bug
/kind cleanup
This follows up the changes of https://github.com/falcosecurity/falco/pull/2430. After that PR is merged, the number of plugins initialized at a given time (holding a valid Handle) will grow during a dry run. As such, the max number of assignable handles has been grown to a reasonably bigger number.
Note that even though MaxHandle influences the implementation of our async extraction optimization, there should be no performance regression due to the sync batch slots being skipped if unused (see: https://github.com/falcosecurity/plugin-sdk-go/blob/3856dc775cc8ab7f0043f51d5bd7191b72454339/pkg/sdk/symbols/extract/async.go#L187). …
=> update(pkg/cgo): set MaxHandle to 255

examples/custom/go.sum, examples/extractor/go.sum, examples/full/go.sum, examples/source/go.sum, pkg/sdk/extract.go, pkg/sdk/extract_test.go
/kind bug
When writing res data into a `ss_plugin_extract_field`, we allocate an array batch that we reuse from request to request. We used to compute the offset of each result "slot" by assuming that each value always had the same size as the union of results, because by supporting only a char pointer and uint64 all values had the same size. This guarantee stopped being true when we introduced `ss_plugin_byte_buffer`, which now forces us to compute the right result slot offsets depending on the type data size, which is the right thing to do anyways. The framework will expect the result to be a contiguous array of …
=> fix(pkg/sdk): solve memory alignment issues when setting extraction value

examples/custom/go.sum, examples/extractor/go.sum, examples/full/go.sum, examples/source/go.sum, go.mod, go.sum, pkg/loader/loader.go
/kind cleanup
The `go.uber.org/multierr` dependency made our SDK require Go version >= 1.19. Since we don't really need it, it's best for us to just drop the dependency and stick to an older Go version requirement.
```release-note
update: drop go.uber.org/multierr dependency
```
=> update: drop go.uber.org/multierr dependency

benchmarks/async/Makefile, examples/custom/Makefile, examples/extractor/Makefile, examples/full/Makefile, examples/source/Makefile, pkg/sdk/strlcpy.h
/kind bug
> /kind design
/area build
> /area plugin-sdk
> /area tests
Fixes #
```release-note
fix: solve compilation errors with glibc 2.38 and Go 1.21
```
=> fix compilation errors with latest glibc and Go versions

pkg/cgo/handle.go, pkg/cgo/handle_test.go, pkg/sdk/symbols/extract/async.go
/kind bug
/kind cleanup
Due to how shared object loading works in Linux and in the falcosecurity libs, I discovered that concurrent (and legitimate, as per generalized non-Falco libs consumers) operations to plugins written in Go led to panics and segfaults caused by data races in case of many workers.
So far my research led to discovering that this kind of issues disappear when re-working the `cgo.Handle` primitives to support proper synchronization.
```release-note
fix(pkg/cgo): solve data races when assigning/deleting and …
```
=> fix(pkg/cgo): solve data races when assigning/deleting and accessing handles

.github/workflows/ci.yml
> /kind bug
> /kind design
/kind feature
/area build
> /area plugin-sdk
> /area tests
Part of #77 
```release-note
NONE
```
=> Feature: Added a job in ci which builds the all examples

Makefile, go.mod, pkg/loader/plugin_api_include.patch, pkg/loader/plugin_loader.c, pkg/loader/plugin_loader.h, pkg/loader/strlcpy.patch, pkg/sdk/event.go, pkg/sdk/extract.go, pkg/sdk/extract_test.go, pkg/sdk/plugin_api.h, pkg/sdk/plugin_types.h, pkg/sdk/plugin_types_include.patch, pkg/sdk/plugins/extractor/extractor_test.go, pkg/sdk/symbols/extract/async.go, pkg/sdk/symbols/extract/extract.c, pkg/sdk/symbols/extract/extract.go, pkg/sdk/symbols/extract/extract.h, pkg/sdk/symbols/extract/extract_test.go
Add support for setting value offsets during extraction.
> /kind bug
> /kind design
/kind feature
> /area build
> /area tests
This makes it possible to extend extractor plugins so that they can provide the location of each field in each event or log message.
Fixes #
```release-note
update(pkg/sdk): add field metadata support
```
=> update(api): Add value offset support
